server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/shop
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.type: trace